# Baseline:
## Generate baseline from XSD
- soya.framework.tools.xmlbeans.XmlSchemaBaseLoader:
    source: D:/Workshop/Repository/CMM/BOD/GetDeliverySlot.xsd

# Annotations:
## Apply basic annotation from xlsx mapping sheet:
- soya.framework.tools.xmlbeans.XlsxMappingAnnotator:
    sourceFiles:
      - D:/Workshop/Repository/BusinessObjects/DeliverySlot/requirement/input.json
    mappingFile: D:/Workshop/Repository/BusinessObjects/DeliverySlot/requirement/DeliverySlot_OSMS_TO_EDIS_Canonical_Mapping_v1.2.2.xlsx
    mappingSheet: "Mapping Source to Canonical"

## Fix unknown mappings: target paths, source paths and mapping rules...
- soya.framework.tools.xmlbeans.UnknownMappingFixAnnotator:

## Special scenarios of node annotation: blocks, loops, constructions, sub procedures...
- soya.framework.tools.xmlbeans.NodeConstructionAnnotator:
    path: GetDeliverySlot/DeliverySlotData/DeliveryChargeType
    sourcePath: b2bCharge
    variable: _b2bCharge
    assignments:
      CustomerType/Code: _b2bCharge.userType
      DeliveryChargeAmt: CAST(_b2bCharge.deliveryCharge AS DECIMAL(6, 2))
      DiscountedDeliveryChargeAmt: CAST(_b2bCharge.reducedDeliveryCharge AS DECIMAL(6, 2))
      DeliveryChargeId: _b2bCharge.deliveryChargeUPC
      DiscountedDeliveryChargeId: _b2bCharge.reducedDeliveryChargeUPC
      BasketSizeCnt: _b2bCharge.minimumBasketSize
      AlertBasketSizeCnt: _b2bCharge.alertBasketSize

- soya.framework.tools.xmlbeans.NodeConstructionAnnotator:
    path: GetDeliverySlot/DeliverySlotData/DeliveryChargeType
    sourcePath: b2cCharge
    variable: _b2cCharge
    assignments:
      CustomerType/Code: _b2cCharge.userType
      DeliveryChargeAmt: CAST(_b2cCharge.deliveryCharge AS DECIMAL(6, 2))
      DiscountedDeliveryChargeAmt: CAST(_b2cCharge.reducedDeliveryCharge AS DECIMAL(6, 2))
      DeliveryChargeId: _b2cCharge.deliveryChargeUPC
      DiscountedDeliveryChargeId: _b2cCharge.reducedDeliveryChargeUPC
      BasketSizeCnt: _b2cCharge.minimumBasketSize
      AlertBasketSizeCnt: _b2cCharge.alertBasketSize

## Generate assignments:
- soya.framework.tools.xmlbeans.AssignmentAnnotator:
    globalVariables:
      - name: VERSION_ID
        type: CHARACTER
        defaultValue: "'1.2.2.023'"
      - name: SYSTEM_ENVIRONMENT_CODE
        type: CHARACTER
        defaultValue: "'PROD'"
    autoAnnotateLoop: true
    assignments:
      - GetDeliverySlot/DocumentData/Document/@VersionId: VERSION_ID
      - GetDeliverySlot/DocumentData/Document/@SystemEnvironmentCd: SYSTEM_ENVIRONMENT_CODE
      - GetDeliverySlot/DocumentData/Document/DocumentID: "'DeliverySlot'"
      - GetDeliverySlot/DocumentData/Document/AlternateDocumentID: "'DeliverySlot_' || CAST(CURRENT_TIMESTAMP AS CHARACTER FORMAT 'YYYYMMddHHmmssSSSSSS')"
      - GetDeliverySlot/DocumentData/Document/CreationDt: CURRENT_TIMESTAMP

## Apply functions based on special rules:
- soya.framework.tools.xmlbeans.DecimalFunctionAnnotator:

# Renderers:
## Print all XPaths:
- soya.framework.tools.xmlbeans.XPathRenderer:
    name: XPath

## Print Sample XML:
- soya.framework.tools.xmlbeans.SampleXmlRenderer:
    name: SampleXml

## Print node tree in json, indexed by xpath:
- soya.framework.tools.xmlbeans.JsonMappingRenderer:
    name: JsonMapping

## Print Base Annotation, eg. Unknown mappings:
- soya.framework.tools.xmlbeans.BaseAnnotationRenderer:
    name: UnknownMappings
    annotation: UNKNOWN_MAPPINGS

## Print XML construct tree:
- soya.framework.tools.xmlbeans.XmlConstructTreeRenderer:
    name: XmlConstructTree

- soya.framework.tools.xmlbeans.AssignmentRenderer:


- soya.framework.tools.xmlbeans.LoopAnalyzeRenderer:
    name: LoopAnalyze

## Print ESQL
- soya.framework.tools.xmlbeans.XmlConstructEsqlRenderer:
    name: ESQL
    brokerSchema: com.abs.osms.deliveryslot
    moduleName: ESED_DELIVERYSLOT_OSMS_CMM_Compute
    inputRootVariable: _inputRootNode
    inputRootReference: InputRoot.JSON.Data

## Print transformation output xml:
- soya.framework.tools.xmlbeans.XmlMessageRenderer:
    inputMessageFile: D:/Workshop/Repository/BusinessObjects/DeliverySlot/requirement/input.json

## Print Avro Schema
- soya.framework.tools.xmlbeans.AvroSchemaRenderer:
    name: AvroSchema

## Print deployment artifacts:
- soya.framework.tools.xmlbeans.OverwritePropertiesRenderer:
    name: DEVOverwriteProperties
    properties:
      ESED_DELIVERYSLOT_OSMS_CMM.SYSTEM_ENVIRONMENT_CODE: DEV

- soya.framework.tools.xmlbeans.OverwritePropertiesRenderer:
    name: QAOverwriteProperties
    properties:
      ESED_DELIVERYSLOT_OSMS_CMM.SYSTEM_ENVIRONMENT_CODE: QA