- soya.framework.tools.xmlbeans.XmlSchemaBaseLoader:
    source: D:/Workshop/Repository/CMM/BOD/GetDeliverySlot.xsd

- soya.framework.tools.xmlbeans.XlsxMappingAnnotator:
    sourceFiles:
      - D:/Workshop/Repository/BusinessObjects/DeliverySlot/requirement/input.json
    mappingFile: D:/Workshop/Repository/BusinessObjects/DeliverySlot/requirement/DeliverySlot_OSMS_TO_EDIS_Canonical_Mapping_v1.1.1.xlsx
    mappingSheet: "Mapping Source to Canonical"


- soya.framework.tools.xmlbeans.DecimalFunctionAnnotator:

- soya.framework.tools.xmlbeans.XPathRenderer:

- soya.framework.tools.xmlbeans.XmlConstructTreeRenderer:

- soya.framework.tools.xmlbeans.BaseAnnotationRenderer:
    name: UnknownMappings
    annotation: UNKNOWN_MAPPINGS

- soya.framework.tools.xmlbeans.JsonMappingRenderer:
- soya.framework.tools.xmlbeans.AssignmentRenderer:
- soya.framework.tools.xmlbeans.LoopAnalyzeRenderer:
- soya.framework.tools.xmlbeans.SampleXmlRenderer:
- soya.framework.tools.xmlbeans.XmlMessageRenderer:
    inputMessageFile: D:/Workshop/Repository/BusinessObjects/DeliverySlot/requirement/input.json

- soya.framework.tools.xmlbeans.AvroSchemaRenderer:

- soya.framework.tools.xmlbeans.XmlConstructEsqlRenderer:
    brokerSchema: com.abs.osms.deliveryslot
    moduleName: ESED_DELIVERYSLOT_OSMS_CMM_Compute
    inputRootVariable: _inputRootNode
    inputRootReference: InputRoot.JSON.Data

- soya.framework.tools.xmlbeans.OverwritePropertiesRenderer:
    name: DEVOverwriteProperties
    properties:
      ESED_DELIVERYSLOT_OSMS_CMM.SYSTEM_ENVIRONMENT_CODE: DEV


- soya.framework.tools.xmlbeans.OverwritePropertiesRenderer:
    name: QAOverwriteProperties
    properties:
      ESED_DELIVERYSLOT_OSMS_CMM.SYSTEM_ENVIRONMENT_CODE: QA