- soya.framework.tools.xmlbeans.XmlSchemaBaseLoader:
    source: "D:/Workshop/Repository/CMM/BOD/GetGroceryOrder.xsd"

- soya.framework.tools.xmlbeans.XlsxMappingAnnotator:
    url: "D:/Workshop/Repository/BusinessObjects/GroceryOrder/requirement/GroceryOrder_ERUMS_to_Canonical_Mapping_v1.4.1.xlsx"
    sheet: "Mapping Source to Canonical"
    excludes:
      - GetGroceryOrder/GroceryOrderData/GroceryOrderHeader/RetailCustomer/Contact/Address
      - GetGroceryOrder/GroceryOrderData/GrocerySubOrder/DeliveryPromotion
      - GetGroceryOrder/GroceryOrderData/GrocerySubOrder/GroceryOrderDetail/PromotionTxt
      - GetGroceryOrder/GroceryOrderData/GrocerySubOrder/GroceryOrderDetail/PromotionalDsc
      - GetGroceryOrder/GroceryOrderData/GrocerySubOrder/GroceryOrderDetail/PromotionPriceAmt

- soya.framework.tools.xmlbeans.AssignmentAnnotator:
    globalVariables:
      - name: SYSTEM_ENVIRONMENT_CODE
        type: CHARACTER
        defaultValue: "'PROD'"
    loops:
      - sourcePath: customer/contact[*]
        targetPath: GetGroceryOrder/GroceryOrderData/GroceryOrderHeader/RetailCustomer/Contact
        name: contact
        variable: _contact

      - sourcePath: customer/email[*]
        targetPath: GetGroceryOrder/GroceryOrderData/GroceryOrderHeader/RetailCustomer/Contact
        name: email
        variable: _email

      - sourcePath: customer/address[*]
        targetPath: GetGroceryOrder/GroceryOrderData/GroceryOrderHeader/RetailCustomer/Contact
        name: address
        variable: _address

      - sourcePath: customer/preference/optIn[*]
        targetPath: GetGroceryOrder/GroceryOrderData/GroceryOrderHeader/RetailCustomer/CustomerPreference
        name: optIn
        variable: _optIn

      - sourcePath: paymentDetails[*]
        targetPath: GetGroceryOrder/GroceryOrderData/GroceryOrderHeader/CustomerPayment/Tender
        name: paymentDetails
        variable: _paymentDetails

      - sourcePath: tender[*]
        targetPath: GetGroceryOrder/GroceryOrderData/GroceryOrderHeader/CustomerPayment/Tender/Refund
        name: tender
        variable: _tender

      - sourcePath: orderTotal/cardSavings[*]
        targetPath: GetGroceryOrder/GroceryOrderData/GroceryOrderHeader/CustomerSavings/SavingsCategoryType
        name: card_savings
        variable: _card_savings

      - sourcePath: subOrders[*]
        targetPath: GetGroceryOrder/GroceryOrderData/GrocerySubOrder
        name: subOrder
        variable: _subOrder

      - sourcePath: subOrders[*]/orderLines[*]
        targetPath: GetGroceryOrder/GroceryOrderData/GrocerySubOrder/GroceryOrderDetail
        name: orderLine
        variable: _orderLine

      - sourcePath: subOrders[*]/promoCodes[*]
        targetPath: GetGroceryOrder/GroceryOrderData/GrocerySubOrder/GroceryOrderDetail
        name: promoCode
        variable: _promoCode

      - sourcePath: subOrders[*]/refundedOrderLines[*]
        targetPath: GetGroceryOrder/GroceryOrderData/GrocerySubOrder/ReturnedItem
        name: refundedOrderLine
        variable: _refundedOrderLine

      - sourcePath: subOrders[*]/charges[*]
        targetPath: GetGroceryOrder/GroceryOrderData/GrocerySubOrder/ChargeInfo
        name: charge
        variable: _charge

      - sourcePath: subOrders[*]/customerService/contact[*]
        targetPath: GetGroceryOrder/GroceryOrderData/GrocerySubOrder/CustomerService
        name: service_contact
        variable: _service_contact

      - sourcePath: subOrders[*]/orderLines[*]/itemPrice/savings[*]
        targetPath: GetGroceryOrder/GroceryOrderData/GrocerySubOrder/GroceryOrderDetail/CustomerOffers
        name: customer_savings_loop
        variable: _customer_savings

      - sourcePath: subOrders[*]/orderLines[*]/itemPrice/savings[*]/points[*]
        targetPath: GetGroceryOrder/GroceryOrderData/GrocerySubOrder/GroceryOrderDetail/CustomerOffers/CustomerRewards
        name: points_loop
        variable: _point

    assignments:
      - GetGroceryOrder/DocumentData/Document/@SystemEnvironmentCd: SYSTEM_ENVIRONMENT_CODE
      - GetGroceryOrder/DocumentData/Document/DocumentID: "'GROCERY_ORDER'"
      - GetGroceryOrder/DocumentData/Document/AlternateDocumentID: "'OSMS-EMOM_C02_ORDER-' || CAST(CURRENT_TIMESTAMP AS CHARACTER FORMAT 'YYYYMMddHHmmssSSSSSS')"
      - GetGroceryOrder/DocumentData/Document/DocumentNm: "'GroceryOrder'"
      - GetGroceryOrder/DocumentData/Document/CreationDt: "CAST(CURRENT_TIMESTAMP AS CHARACTER FORMAT 'YYYYMMdd_HH:mm:ss')"

      - GetGroceryOrder/GroceryOrderData/GroceryOrderHeader/CustomerPayment/Tender/RequiredAuthAmt: CAST($$ AS DECIMAL(10, 2))

      - GetGroceryOrder/GroceryOrderData/GroceryOrderHeader/RetailCustomer/Contact/PhoneFaxContact/@TypeCode: _contact.type
      - GetGroceryOrder/GroceryOrderData/GroceryOrderHeader/CustomerPayment/Tender/ExpireMonthYearTxt:  _paymentDetails.cardExpiryMonth
      - GetGroceryOrder/GroceryOrderData/GrocerySubOrder/ChargeInfo/ChargeAmt: CAST($$ AS DECIMAL(10, 2))


- soya.framework.tools.xmlbeans.DecimalFunctionAnnotator:

- soya.framework.tools.xmlbeans.NodeBuildAnnotator:
    path: GetGroceryOrder/GroceryOrderData/GroceryOrderHeader/FulfillingFacility
    block:
      RetailStoreId: $.storeNumber
      BannerCd: $.banner
      _while:
        sourcePath: storeInfo[*]
        name: store_info
        variable: _storeInfo
        block:
          MFCInd: "'???'"
          HybridStoreInd: "'???'"
          PremiumStoreInd: "'???'"
          ThirdPartyDeliveryOnlyInd: "'???'"
          ERUMSEnabledInd: "'???'"

- soya.framework.tools.xmlbeans.SampleXmlRenderer:

- soya.framework.tools.xmlbeans.XPathRenderer:
    printUnmapped: true

- soya.framework.tools.xmlbeans.JsonMappingRenderer:
- soya.framework.tools.xmlbeans.LoopAnalyzeRenderer:
- soya.framework.tools.xmlbeans.AvroSchemaRenderer:

- soya.framework.tools.xmlbeans.EsqlRenderer:
    brokerSchema: com.abs.erums.groceryorder
    moduleName: ESED_GroceryOrder_CMM_Transformer_Compute
    inputRootVariable: _inputRootNode
    inputRootReference: InputRoot.JSON.Data
