# Baseline:
## Generate baseline from XSD
- soya.framework.tools.xmlbeans.XmlSchemaBaseLoader:
    source: CMM/BOD/GetGroceryOrder.xsd

# Annotations:
## Apply basic annotation from xlsx mapping sheet:
- soya.framework.tools.xmlbeans.XlsxMappingAnnotator:
    sourceFiles: # load source json from files
      - BusinessObjects/GroceryOrder/requirement/oms.json

    mappingFile: BusinessObjects/GroceryOrder/requirement/GroceryOrder_ERUMS_to_Canonical_Mapping_v1.5.1.xlsx
    mappingSheet: "Mapping OMS to Canonical"
    excludes: # mappings defined but not in this version
      - GetGroceryOrder/GroceryOrderData/GroceryOrderHeader/RetailCustomer/Contact/Address/PhoneNbr
      - GetGroceryOrder/GroceryOrderData/GroceryOrderHeader/RetailCustomer/Contact/PhoneFaxContact/PhoneNbr


## Apply node attribute changes:
- soya.framework.tools.xmlbeans.XmlSchemaNodeAnnotator:
    nodes:
      GetGroceryOrder/DocumentData/Document:
        namespaceURI: http://collab.safeway.com/it/architecture/info/default.aspx
      GetGroceryOrder/DocumentData/DocumentAction:
        namespaceURI: http://collab.safeway.com/it/architecture/info/default.aspx
      GetGroceryOrder/GroceryOrderData/GrocerySubOrder/GroceryOrderDetail/DeliveredItem:
        cardinality: 0-n

## Fix unknown mappings: target paths, source paths and mapping rules...
- soya.framework.tools.xmlbeans.UnknownMappingFixAnnotator:
    fixes:
      ### unknown target paths:
      - unknownType: UNKNOWN_TARGET_PATH
        targetPath: GetGroceryOrder/DocumentData/Document/SystemEnvironmentCd
        fix: GetGroceryOrder/DocumentData/Document/@SystemEnvironmentCd

      - unknownType: UNKNOWN_TARGET_PATH
        targetPath: GetGroceryOrder/GroceryOrderData/GroceryOrderHeader/EditCutoffDttm
        fix: GetGroceryOrder/GroceryOrderData/GroceryOrderHeader/EditCutoffDtTm

      - unknownType: UNKNOWN_TARGET_PATH
        targetPath: GetGroceryOrder/GroceryOrderData/GroceryOrderHeader/RetailCustomer/CustomerAlternateId/sequenceNbr
        fix: GetGroceryOrder/GroceryOrderData/GroceryOrderHeader/RetailCustomer/CustomerAlternateId/@sequenceNbr

      - unknownType: UNKNOWN_TARGET_PATH
        targetPath: GetGroceryOrder/GroceryOrderData/GroceryOrderHeader/RetailCustomer/Contact/PhoneFaxContact/TypeCode
        fix: GetGroceryOrder/GroceryOrderData/GroceryOrderHeader/RetailCustomer/Contact/PhoneFaxContact/@TypeCode

      - unknownType: UNKNOWN_TARGET_PATH
        targetPath: GetGroceryOrder/GroceryOrderData/GroceryOrderHeader/RetailCustomer/Contact/DigitalContact/EmailStatuses/typeCode
        fix: GetGroceryOrder/GroceryOrderData/GroceryOrderHeader/RetailCustomer/Contact/DigitalContact/EmailStatuses/@typeCode

      - unknownType: UNKNOWN_TARGET_PATH
        targetPath: GetGroceryOrder/GroceryOrderData/GroceryOrderHeader/CustomerNotesTxt/typeCode
        fix: GetGroceryOrder/GroceryOrderData/GroceryOrderHeader/CustomerNotesTxt/@typeCode

      - unknownType: UNKNOWN_TARGET_PATH
        targetPath: GetGroceryOrder/GroceryOrderData/GrocerySubOrder/DeliveryInfo/EditCutoffDttm
        fix: GetGroceryOrder/GroceryOrderData/GrocerySubOrder/DeliveryInfo/EditCutoffDtTm

      - unknownType: UNKNOWN_TARGET_PATH
        targetPath: GetGroceryOrder/GroceryOrderData/GrocerySubOrder/DeliveryInfo/DeliverytimeZoneCd
        fix: GetGroceryOrder/GroceryOrderData/GrocerySubOrder/DeliveryInfo/DeliveryTimeZoneCd

      - unknownType: UNKNOWN_TARGET_PATH
        targetPath: GetGroceryOrder/GroceryOrderData/GrocerySubOrder/CustomerService/PhoneFaxContact/TypeCode
        fix: GetGroceryOrder/GroceryOrderData/GrocerySubOrder/CustomerService/PhoneFaxContact/@TypeCode

      - unknownType: UNKNOWN_TARGET_PATH
        targetPath: GetGroceryOrder/GroceryOrderData/GrocerySubOrder/GroceryOrderDetail/DeliveredItem/PromotionalPriceAmt
        fix: GetGroceryOrder/GroceryOrderData/GrocerySubOrder/GroceryOrderDetail/DeliveredItem/PromotionPriceAmt

      - unknownType: UNKNOWN_TARGET_PATH
        targetPath: GetGroceryOrder/GroceryOrderData/GrocerySubOrder/GroceryOrderDetail/FulFilledQty
        fix: GetGroceryOrder/GroceryOrderData/GrocerySubOrder/GroceryOrderDetail/FulfilledQty

      ### unknown source path:
      - unknownType: UNKNOWN_SOURCE_PATH
        targetPath: GetGroceryOrder/GroceryOrderData/GroceryOrderHeader/RetailCustomer/Contact/Address/PostalZoneCd
        fix: customer/address[*]/zipCode


## Special scenarios of node annotation: loops, constructions, blocks, sub procedures...
- soya.framework.tools.xmlbeans.NodeLoopsAnnotator:
    path: GetGroceryOrder/GroceryOrderData/GroceryOrderHeader/RetailCustomer/CustomerPreference
    condition: _optIn.isOptin = 'true'
    loops:
      - sourcePath: customer/preference/optIn[*]
        name: optIn
        variable: _optIn

- soya.framework.tools.xmlbeans.NodeLoopsAnnotator:
    path: GetGroceryOrder/GroceryOrderData/GroceryOrderHeader/CustomerOffers
    loops:
      - sourcePath: orderTotal/txnLevelSavings[*]
        name: txnLevelSaving
        variable: _txnLevelSaving

- soya.framework.tools.xmlbeans.NodeLoopsAnnotator:
    path: GetGroceryOrder/GroceryOrderData/GroceryOrderHeader/RetailCustomer/Contact
    loops:
      - sourcePath: customer/contact[*]
        name: contact
        variable: _contact

      - sourcePath: customer/email[*]
        name: email
        variable: _email

      - sourcePath: customer/address[*]
        name: address
        variable: _address

- soya.framework.tools.xmlbeans.NodeLoopsAnnotator:
    path: GetGroceryOrder/GroceryOrderData/GroceryOrderHeader/CustomerPayment/Tender
    loops:
      - sourcePath: paymentDetails[*]
        name: paymentDetails
        variable: _paymentDetails

      - sourcePath: tender[*]
        name: tender
        variable: _tender

- soya.framework.tools.xmlbeans.NodeLoopsAnnotator:
    path: GetGroceryOrder/GroceryOrderData/GroceryOrderHeader/CustomerSavings/SavingsCategoryType
    loops:
      - sourcePath: orderTotal/cardSavings[*]
        name: card_savings
        variable: _card_savings

- soya.framework.tools.xmlbeans.NodeLoopsAnnotator:
    path: GetGroceryOrder/GroceryOrderData/GroceryOrderHeader/CustomerNotesTxt
    loops:
      - sourcePath: orderInfo/data[*]
        name: order_info_data
        variable: _order_info_data

- soya.framework.tools.xmlbeans.NodeLoopsAnnotator:
    path: GetGroceryOrder/GroceryOrderData/GrocerySubOrder
    loops:
      - sourcePath: subOrders[*]
        name: subOrder
        variable: _subOrder

- soya.framework.tools.xmlbeans.NodeLoopsAnnotator:
    path: GetGroceryOrder/GroceryOrderData/GrocerySubOrder/GroceryOrderDetail
    loops:
      - sourcePath: subOrders[*]/orderLines[*]
        name: orderLine
        variable: _orderLine

      - sourcePath: subOrders[*]/promoCodes[*]
        name: promoCode
        variable: _promoCode

- soya.framework.tools.xmlbeans.NodeLoopsAnnotator:
    path: GetGroceryOrder/GroceryOrderData/GrocerySubOrder/GroceryOrderDetail/CustomerOffers
    loops:
      - sourcePath: subOrders[*]/orderLines[*]/itemPrice/savings[*]
        name: customer_savings_loop
        variable: _customer_savings

- soya.framework.tools.xmlbeans.NodeLoopsAnnotator:
    path: GetGroceryOrder/GroceryOrderData/GrocerySubOrder/GroceryOrderDetail/CustomerOffers/CustomerRewards
    loops:
      - sourcePath: subOrders[*]/orderLines[*]/itemPrice/savings[*]/points[*]
        name: points_loop
        variable: _point

- soya.framework.tools.xmlbeans.NodeLoopsAnnotator:
    path: GetGroceryOrder/GroceryOrderData/GrocerySubOrder/GroceryOrderDetail/DeliveredItem
    loops:
      - sourcePath: subOrders[*]/orderLines[*]/fulfilledUpc[*]
        name: fulfilled_upc_loop
        variable: _fulfilled_upc

- soya.framework.tools.xmlbeans.NodeLoopsAnnotator:
    path: GetGroceryOrder/GroceryOrderData/GrocerySubOrder/GroceryOrderDetail/DeliveredItem/CustomerOffers
    loops:
      - sourcePath: subOrders[*]/orderLines[*]/fulfilledUpc[*]/itemPrice/savings[*]
        name: fulfilled_upc_savings_loop
        variable: _fulfilled_upc_savings

- soya.framework.tools.xmlbeans.NodeLoopsAnnotator:
    path: GetGroceryOrder/GroceryOrderData/GrocerySubOrder/GroceryOrderDetail/DeliveredItem/CustomerOffers/CustomerRewards
    loops:
      - sourcePath: subOrders[*]/orderLines[*]/fulfilledUpc[*]/itemPrice/savings[*]/points[*]
        name: fulfilled_upc_savings_points_loop
        variable: _fulfilled_upc_savings_point

- soya.framework.tools.xmlbeans.NodeLoopsAnnotator:
    path: GetGroceryOrder/GroceryOrderData/GrocerySubOrder/ReturnedItem
    loops:
      - sourcePath: subOrders[*]/refundedOrderLines[*]
        name: refundedOrderLine
        variable: _refundedOrderLine

- soya.framework.tools.xmlbeans.NodeLoopsAnnotator:
    path: GetGroceryOrder/GroceryOrderData/GrocerySubOrder/ChargeInfo
    loops:
      - sourcePath: subOrders[*]/charges[*]
        name: charge
        variable: _charge

- soya.framework.tools.xmlbeans.NodeLoopsAnnotator:
    path: GetGroceryOrder/GroceryOrderData/GrocerySubOrder/CustomerService
    loops:
      - sourcePath: subOrders[*]/customerService/contact[*]
        name: service_contact
        variable: _service_contact


- soya.framework.tools.xmlbeans.NodeCodeBlockAnnotator:
    path: GetGroceryOrder/GroceryOrderData/GroceryOrderHeader/RetailCustomer/CustomerSubscription
    block:
      - "IF _inputRootNode.customer.isSubscription = 'true' THEN"
      - ""
      - "+ -- GetGroceryOrder/GroceryOrderData/GroceryOrderHeader/RetailCustomer/CustomerSubscription/SubscriptionTypeCd"
      - "+ SET CustomerSubscription_.(XMLNSC.Field)Abs:SubscriptionTypeCd = 'Subscription';"
      - ""
      - "+ -- GetGroceryOrder/GroceryOrderData/GroceryOrderHeader/RetailCustomer/CustomerSubscription/OptInInd"
      - "+ SET CustomerSubscription_.(XMLNSC.Field)Abs:OptInInd = 'true';"
      - ""
      - "ELSE"
      - ""
      - "+ SET CustomerSubscription_.(XMLNSC.Field)Abs:OptInInd = 'false';"
      - ""
      - "END IF;"

- soya.framework.tools.xmlbeans.NodeProcedureAnnotator:
    path: GetGroceryOrder/GroceryOrderData/GroceryOrderHeader/FulfillingFacility
    procedure: ConstructFulfillingFacility
    parameters:
      - name: _inputRootNode
      - name: FulfillingFacility_
        assignment: GroceryOrderHeader_.FulfillingFacility
      - name: GroceryOrderHeader_
    body: CgkJCQkJLS0gR2V0R3JvY2VyeU9yZGVyL0dyb2NlcnlPcmRlckRhdGEvR3JvY2VyeU9yZGVySGVhZGVyL0Z1bGZpbGxpbmdGYWNpbGl0eS9SZXRhaWxTdG9yZUlkCgkJCQkJU0VUIEZ1bGZpbGxpbmdGYWNpbGl0eV8uKFhNTE5TQy5GaWVsZClBYnM6UmV0YWlsU3RvcmVJZCA9IF9pbnB1dFJvb3ROb2RlLnN0b3JlTnVtYmVyOwoKCQkJCQktLSBHZXRHcm9jZXJ5T3JkZXIvR3JvY2VyeU9yZGVyRGF0YS9Hcm9jZXJ5T3JkZXJIZWFkZXIvRnVsZmlsbGluZ0ZhY2lsaXR5L0Jhbm5lckNkCgkJCQkJU0VUIEZ1bGZpbGxpbmdGYWNpbGl0eV8uKFhNTE5TQy5GaWVsZClBYnM6QmFubmVyQ2QgPSBfaW5wdXRSb290Tm9kZS5iYW5uZXI7CgoJCQkJCS0tIEJVSUxEIEZST00gc3RvcmVJbmZvWypdIFRPIEdldEdyb2NlcnlPcmRlci9Hcm9jZXJ5T3JkZXJEYXRhL0dyb2NlcnlPcmRlckhlYWRlci9GdWxmaWxsaW5nRmFjaWxpdHk6CgkJCQkJREVDTEFSRSBfc3RvcmVJbmZvIFJFRkVSRU5DRSBUTyBfaW5wdXRSb290Tm9kZS5zdG9yZUluZm8uSXRlbTsKCQkJCQlzdG9yZV9pbmZvIDogV0hJTEUgTEFTVE1PVkUoX3N0b3JlSW5mbykgRE8KCgkJCQkJCS0tIEdldEdyb2NlcnlPcmRlci9Hcm9jZXJ5T3JkZXJEYXRhL0dyb2NlcnlPcmRlckhlYWRlci9GdWxmaWxsaW5nRmFjaWxpdHkvTUZDSW5kCgkJCQkJCUlGIF9zdG9yZUluZm8ua2V5ID0gJ2lzTUZDJyBUSEVOCgkJCQkJCQlJRiBfc3RvcmVJbmZvLnZhbHVlID0gJ3RydWUnIFRIRU4KCQkJCQkJCQlTRVQgRnVsZmlsbGluZ0ZhY2lsaXR5Xy4oWE1MTlNDLkZpZWxkKUFiczpNRkNJbmQgPSAnWSc7CgkJCQkJCQlFTFNFCgkJCQkJCQkJU0VUIEZ1bGZpbGxpbmdGYWNpbGl0eV8uKFhNTE5TQy5GaWVsZClBYnM6TUZDSW5kID0gJ04nOwoJCQkJCQkJRU5EIElGOwoKCQkJCQkJLS0gR2V0R3JvY2VyeU9yZGVyL0dyb2NlcnlPcmRlckRhdGEvR3JvY2VyeU9yZGVySGVhZGVyL0Z1bGZpbGxpbmdGYWNpbGl0eS9IeWJyaWRTdG9yZUluZAoJCQkJCQlFTFNFSUYgX3N0b3JlSW5mby5rZXkgPSAnaXNIeWJyaWRTdG9yZScgVEhFTgoJCQkJCQkJSUYgX3N0b3JlSW5mby52YWx1ZSA9ICd0cnVlJyBUSEVOCgkJCQkJCQkJU0VUIEZ1bGZpbGxpbmdGYWNpbGl0eV8uKFhNTE5TQy5GaWVsZClBYnM6SHlicmlkU3RvcmVJbmQgPSAnWSc7CgkJCQkJCQlFTFNFCgkJCQkJCQkJU0VUIEZ1bGZpbGxpbmdGYWNpbGl0eV8uKFhNTE5TQy5GaWVsZClBYnM6SHlicmlkU3RvcmVJbmQgPSAnTic7CgkJCQkJCQlFTkQgSUY7CgoJCQkJCQktLSBHZXRHcm9jZXJ5T3JkZXIvR3JvY2VyeU9yZGVyRGF0YS9Hcm9jZXJ5T3JkZXJIZWFkZXIvRnVsZmlsbGluZ0ZhY2lsaXR5L1ByZW1pdW1TdG9yZUluZAoJCQkJCQlFTFNFSUYgX3N0b3JlSW5mby5rZXkgPSAnaXNQcmVtaXVtU3RvcmUnIFRIRU4KCQkJCQkJCUlGIF9zdG9yZUluZm8udmFsdWUgPSAndHJ1ZScgVEhFTgoJCQkJCQkJCVNFVCBGdWxmaWxsaW5nRmFjaWxpdHlfLihYTUxOU0MuRmllbGQpQWJzOlByZW1pdW1TdG9yZUluZCA9ICdZJzsKCQkJCQkJCUVMU0UKCQkJCQkJCQlTRVQgRnVsZmlsbGluZ0ZhY2lsaXR5Xy4oWE1MTlNDLkZpZWxkKUFiczpQcmVtaXVtU3RvcmVJbmQgPSAnTic7CgkJCQkJCQlFTkQgSUY7CgoJCQkJCQktLSBHZXRHcm9jZXJ5T3JkZXIvR3JvY2VyeU9yZGVyRGF0YS9Hcm9jZXJ5T3JkZXJIZWFkZXIvRnVsZmlsbGluZ0ZhY2lsaXR5L1RoaXJkUGFydHlEZWxpdmVyeU9ubHlJbmQKCQkJCQkJRUxTRUlGIF9zdG9yZUluZm8ua2V5ID0gJ2lzM1BMU3RvcmUnIFRIRU4KCQkJCQkJCUlGIF9zdG9yZUluZm8udmFsdWUgPSAndHJ1ZScgVEhFTgoJCQkJCQkJCVNFVCBGdWxmaWxsaW5nRmFjaWxpdHlfLihYTUxOU0MuRmllbGQpQWJzOlRoaXJkUGFydHlEZWxpdmVyeU9ubHlJbmQgPSAnWSc7CgkJCQkJCQlFTFNFCgkJCQkJCQkJU0VUIEZ1bGZpbGxpbmdGYWNpbGl0eV8uKFhNTE5TQy5GaWVsZClBYnM6VGhpcmRQYXJ0eURlbGl2ZXJ5T25seUluZCA9ICdOJzsKCQkJCQkJCUVORCBJRjsKCgkJCQkJCS0tIEdldEdyb2NlcnlPcmRlci9Hcm9jZXJ5T3JkZXJEYXRhL0dyb2NlcnlPcmRlckhlYWRlci9GdWxmaWxsaW5nRmFjaWxpdHkvRVJVTVNFbmFibGVkSW5kCgkJCQkJCUVMU0VJRiBfc3RvcmVJbmZvLmtleSA9ICdpc0VydW1zRW5hYmxlZCcgVEhFTgoJCQkJCQkJSUYgX3N0b3JlSW5mby52YWx1ZSA9ICd0cnVlJyBUSEVOCgkJCQkJCQkJU0VUIEZ1bGZpbGxpbmdGYWNpbGl0eV8uKFhNTE5TQy5GaWVsZClBYnM6RVJVTVNFbmFibGVkSW5kID0gJ1knOwoJCQkJCQkJRUxTRQoJCQkJCQkJCVNFVCBGdWxmaWxsaW5nRmFjaWxpdHlfLihYTUxOU0MuRmllbGQpQWJzOkVSVU1TRW5hYmxlZEluZCA9ICdOJzsKCQkJCQkJCUVORCBJRjsKCgkJCQkJCS0tIEdldEdyb2NlcnlPcmRlci9Hcm9jZXJ5T3JkZXJEYXRhL0dyb2NlcnlPcmRlckhlYWRlci9Hcm9jZXJ5T3JkZXJQcm9maWxlVHlwZQoJCQkJCQlFTFNFSUYgX3N0b3JlSW5mby5rZXkgPSAnaXNXWVNJV1lHRW5hYmxlZCcgVEhFTgoJCQkJCQkJSUYgX3N0b3JlSW5mby52YWx1ZSA9ICd0cnVlJyBUSEVOCgoJCQkJCQkJCS0tIEdldEdyb2NlcnlPcmRlci9Hcm9jZXJ5T3JkZXJEYXRhL0dyb2NlcnlPcmRlckhlYWRlci9Hcm9jZXJ5T3JkZXJQcm9maWxlVHlwZQoJCQkJCQkJCURFQ0xBUkUgR3JvY2VyeU9yZGVyUHJvZmlsZVR5cGVfIFJFRkVSRU5DRSBUTyBHcm9jZXJ5T3JkZXJIZWFkZXJfOwoJCQkJCQkJCUNSRUFURSBMQVNUQ0hJTEQgT0YgR3JvY2VyeU9yZGVySGVhZGVyXyBBUyBHcm9jZXJ5T3JkZXJQcm9maWxlVHlwZV8gVFlQRSBYTUxOU0MuRm9sZGVyIE5BTUUgJ0FiczpHcm9jZXJ5T3JkZXJQcm9maWxlVHlwZSc7CgoJCQkJCQkJCQktLSBHZXRHcm9jZXJ5T3JkZXIvR3JvY2VyeU9yZGVyRGF0YS9Hcm9jZXJ5T3JkZXJIZWFkZXIvR3JvY2VyeU9yZGVyUHJvZmlsZVR5cGUvUHJvZmlsZVR5cGUKCQkJCQkJCQkJREVDTEFSRSBQcm9maWxlVHlwZV8gUkVGRVJFTkNFIFRPIEdyb2NlcnlPcmRlclByb2ZpbGVUeXBlXzsKCQkJCQkJCQkJQ1JFQVRFIExBU1RDSElMRCBPRiBHcm9jZXJ5T3JkZXJQcm9maWxlVHlwZV8gQVMgUHJvZmlsZVR5cGVfIFRZUEUgWE1MTlNDLkZvbGRlciBOQU1FICdBYnM6UHJvZmlsZVR5cGUnOwoKCQkJCQkJCQkJCS0tIEdldEdyb2NlcnlPcmRlci9Hcm9jZXJ5T3JkZXJEYXRhL0dyb2NlcnlPcmRlckhlYWRlci9Hcm9jZXJ5T3JkZXJQcm9maWxlVHlwZS9Qcm9maWxlVHlwZS9Db2RlCgkJCQkJCQkJCQlTRVQgUHJvZmlsZVR5cGVfLihYTUxOU0MuRmllbGQpQWJzOkNvZGUgPSAnV1lTSVdZRyc7CgoJCQkJCQkJCQkJLS0gR2V0R3JvY2VyeU9yZGVyL0dyb2NlcnlPcmRlckRhdGEvR3JvY2VyeU9yZGVySGVhZGVyL0dyb2NlcnlPcmRlclByb2ZpbGVUeXBlL1Byb2ZpbGVWYWx1ZUluZAoJCQkJCQkJCQkJU0VUIEdyb2NlcnlPcmRlclByb2ZpbGVUeXBlXy4oWE1MTlNDLkZpZWxkKUFiczpQcm9maWxlVmFsdWVJbmQgPSAndHJ1ZSc7CgkJCQkJCQlFTkQgSUY7CgoJCQkJCQlFTkQgSUY7CgoJCQkJCU1PVkUgX3N0b3JlSW5mbyBORVhUU0lCTElORzsKCQkJCQlFTkQgV0hJTEUgc3RvcmVfaW5mbzsK

- soya.framework.tools.xmlbeans.NodeProcedureAnnotator:
    path: GetGroceryOrder/GroceryOrderData/GroceryOrderHeader/GroceryOrderProfileType
    procedure: ConstructGroceryOrderProfileType
    parameters:
      - name: _inputRootNode
      - name: GroceryOrderProfileType_

##
- soya.framework.tools.xmlbeans.MappingsAnnotator:
    mappings:
      GetGroceryOrder/GroceryOrderData/GroceryOrderHeader/RetailCustomer/CustomerPreference/PreferenceType/Code:
        mapping:
          sourcePath: customer/preference/optIn[*]/type
          mappingRule: Direct Mapping

      GetGroceryOrder/GroceryOrderData/GroceryOrderHeader/CustomerPayment/Tender/Refund:
        condition: _tender.tenderType = 'REFUND'

      GetGroceryOrder/GroceryOrderData/GroceryOrderHeader/CustomerPayment/Tender/Cancellation:
        condition: _tender.tenderType = 'CANCELLATION'

      GetGroceryOrder/GroceryOrderData/GrocerySubOrder/GroceryOrderDetail/ItemId/InternalItemId:
        mapping:
          mappingRule: Direct Mapping
          sourcePath: subOrders[*]/orderLines[*]/itemPrice/itemCode

      GetGroceryOrder/GroceryOrderData/GrocerySubOrder/GroceryOrderDetail/ItemId/BaseProductNbr:
        mapping:
          mappingRule: Direct Mapping
          sourcePath: subOrders[*]/orderLines[*]/itemId

      GetGroceryOrder/GroceryOrderData/GrocerySubOrder/DeliveryInfo/DeliveryTimeZoneCd:
        mapping:
          assignment: _subOrder.deliveryInfo.slotInfo.timeZone

## Generate assignments:
- soya.framework.tools.xmlbeans.AssignmentAnnotator:
    globalVariables:
      - name: VERSION_ID
        type: CHARACTER
        defaultValue: "'1.5.1.057'"
      - name: SYSTEM_ENVIRONMENT_CODE
        type: CHARACTER
        defaultValue: "'PROD'"

    assignments:
      - GetGroceryOrder/DocumentData/Document/@VersionId: VERSION_ID
      - GetGroceryOrder/DocumentData/Document/@SystemEnvironmentCd: SYSTEM_ENVIRONMENT_CODE
      - GetGroceryOrder/DocumentData/Document/DocumentID: "'GROCERY_ORDER'"
      - GetGroceryOrder/DocumentData/Document/AlternateDocumentID: "'OSCO_ESED_C02_ORDER-' || CAST(CURRENT_TIMESTAMP AS CHARACTER FORMAT 'YYYYMMddHHmmssSSSSSS')"
      - GetGroceryOrder/DocumentData/Document/DocumentNm: "'GroceryOrder'"
      - GetGroceryOrder/DocumentData/Document/CreationDt: CURRENT_TIMESTAMP

      - GetGroceryOrder/GroceryOrderData/GroceryOrderHeader/CustomerPayment/Tender/RequiredAuthAmt: CAST($$ AS DECIMAL(10, 2))
      - GetGroceryOrder/GroceryOrderData/GroceryOrderHeader/CustomerPayment/Tender/ExpireMonthYearTxt: _paymentDetails.cardExpiryMonth
      - GetGroceryOrder/GroceryOrderData/GrocerySubOrder/ChargeInfo/ChargeAmt: CAST($$ AS DECIMAL(10, 2))

      - GetGroceryOrder/GroceryOrderData/GroceryOrderHeader/GroceryOrderProfileType/ProfileType/Code: "'taxExempt'"
      - GetGroceryOrder/GroceryOrderData/GroceryOrderHeader/GroceryOrderProfileType/ProfileType/Description: "'???'"
      - GetGroceryOrder/GroceryOrderData/GroceryOrderHeader/GroceryOrderProfileType/ProfileValueInd: "'???'"

- soya.framework.tools.xmlbeans.DecimalFunctionAnnotator:

# Renderers:
## Print all XPaths:
## Print XPaths Mappings:
- soya.framework.tools.xmlbeans.XPathMappingsRenderer:
    name: XPathMappings
    printUnmapped: true

## Print XPaths Assignments:
- soya.framework.tools.xmlbeans.XPathAssignmentsRenderer:
    name: XPathAssignments
    printUnmapped: true

- soya.framework.tools.xmlbeans.SampleXmlRenderer:

- soya.framework.tools.xmlbeans.XmlConstructionRenderer:
    includeUnmapped: false

- soya.framework.tools.xmlbeans.XmlConstructTreeRenderer:

- soya.framework.tools.xmlbeans.BaseAnnotationRenderer:
    name: UnknownMappings
    annotation: UNKNOWN_MAPPINGS

- soya.framework.tools.xmlbeans.JsonMappingRenderer:
- soya.framework.tools.xmlbeans.LoopAnalyzeRenderer:
- soya.framework.tools.xmlbeans.AvroSchemaRenderer:

- soya.framework.tools.xmlbeans.XmlConstructEsqlRenderer:
    brokerSchema: com.abs.oms.groceryorder
    moduleName: ESED_GroceryOrder_OMS_Transformer_Compute
    inputRootVariable: _inputRootNode
    inputRootReference: InputRoot.JSON.Data
